### ISSUE TITLE
Random crashes of the bot after problems occur connected to requests

### ISSUE THREAD

**Issue by julianYaman** [julianYaman/wikipedia-bot#45]
**Describe the problem you experienced in as much detail as possible:**
The recent crash was related to errors happened while trying to make requests. 
This leads to the overloading I saw when looking into the monitoring details of my server.
It seems like these errors lead to a high RAM and CPU usage because of an actual unknown reason.

More investigation is necessary to solve this problem.

**Expected behavior**
That there should be better error handling and no overloading.

**Details:**
 - OS: Ubuntu 16.04
 - Node.js version: v12.16.1
 - Version: `master`

- [x] I installed the used the bot according to the [contributing guidelines.](https://github.com/julianYaman/wikipedia-bot/blob/master/docs/CONTRIBUTING.md)
- [x] I updated every dependecy to its latest release with `npm update --save`

**Comment by MeerBiene** [comment]
PROPOSAL:

Im thinking that response caching could help with this issue, since the possibility that multiple users on multiple guilds are searching for the same keyword isnt too low. My proposal is to have an article caching system that caches articles. We would then save a LastValidCheck timestamp so if theres a request for a keyword and we have the cached article, we can see if we have to validate the article. If we have to, we simply just query the wikipedia api for the latest revisions of the desired article and see if anything changed, if so, we pull the article again, otherwise we send the cached version of the article.

**Comment by julianYaman** [comment]
Hi @MeerBiene, this could actually help in some sort and would definitely make the performance of the bot much better.
